chains:
  - name: arm
    topic: /joint_traj_vel_controller/follow_joint_trajectory
    joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6
    planning_group: manipulator
  - name: chuck
    joints:
      -chuck
duration: 5.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth/color/points
    camera_sensor_name: camera
    chain_sensor_name: arm
