verbose: true
base_link: base_link
models:
 - name: arm
   type: camera_3d
   frame: camera_depth_optical_frame
 - name: chuck
   type: chain
   frame: chuck
free_params:
 - camera_fx
 - camera_fy
 - camera_cx
 - camera_xy
 - camera_z_offset
 - camera_z_scaling
free_frames:
 - name: chuck
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: head_camera_rgb_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: checkerboard
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
free_frames_initial_values:
 - names: checkerboard
   x: 0.6
   y: 0.0
   z: 0.2
   roll: 0.0
   pitch: 0.0
   yaw: -1.57
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: arm
   model_b: board
 - name: restrict_camera
   type: outrageous
   param: head_camera_rgb_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
